# Site settings
title: Naecker Lab
email: jnaecker@wesleyan.edu
description: > # this means to ignore newlines until "baseurl:"
  Experimental economics research lab at Wesleyan University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://naecker-lab.github.io" 
twitter_username: jnaecker
github_username:  naecker-lab

# Build settings
markdown: kramdown
