# Site settings
title: Naecker Lab
email: jnaecker@wesleyan.edu
description: > # this means to ignore newlines until "baseurl:"
  Experimental economics research lab at Wesleyan University.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: jnaecker
github_username:  naecker-lab
author: "Jeffrey Naecker"

# Build settings
markdown: kramdown
